### ISSUE TITLE
Default FirebaseApp is not initialized in this process

### ISSUE THREAD

**Issue by elfefe** [sendbird/SendBird-Android#55]
Hey !

I just build the syncmanager version of this sendbird app sample. I launched it, enter a random id and nickname and add this "$title" error up there in the logcat. It don't realy look like i's because of the random ID, i looked around the doc a bit and this is explained nowere, at list not for this "Example app".

I don't realy now firebase and didn't found anything on the web, can you help me ? 

Full error: 

`2019-06-13 00:05:35.267 17450-17450/com.sendbird.syncmanager.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sendbird.syncmanager.sample, PID: 17450
    java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.sendbird.syncmanager.sample. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@16.0.2:240)
        at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source:1)
        at com.sendbird.syncmanager.sample.utils.PushUtils.registerPushTokenForCurrentUser(PushUtils.java:11)
        at com.sendbird.syncmanager.sample.main.LoginActivity.updateCurrentUserPushToken(LoginActivity.java:131)
        at com.sendbird.syncmanager.sample.main.LoginActivity.access$700(LoginActivity.java:23)
        at com.sendbird.syncmanager.sample.main.LoginActivity$2.onConnected(LoginActivity.java:117)
        at com.sendbird.syncmanager.sample.main.ConnectionManager$1.onConnected(ConnectionManager.java:18)
        at com.sendbird.android.SendBird$10.run(SendBird.java:1345)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by AlexPrestonSB** [comment]
Hey @elfefe, so I looked into this. I think it has to do with a compatibility issue with google services. I will look into getting it fixed. In the mean time to get it working, can you either upgrade or downgrade your google service to 4.2.0 or 4.0.0. This should be in your project level gradle file. See attached. 
![Screen Shot 2019-06-12 at 3 38 20 PM](https://user-images.githubusercontent.com/50602013/59391100-25915300-8d28-11e9-910c-94edc4472811.png)

**Comment by elfefe** [comment]
Yes it works ! Thanks you very much mate ^^

**Comment by AlexPrestonSB** [comment]
No problem!
